# Generated by Django 2.2.10 on 2020-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=200),
        ),
    ]
