# Generated by Django 2.2.10 on 2020-03-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nombre',
            field=models.CharField(default='ninguno', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
