# Generated by Django 3.0.3 on 2020-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200311_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='descripcion',
            field=models.CharField(default='algo', max_length=100),
            preserve_default=False,
        ),
    ]
