# Generated by Django 3.0.3 on 2020-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_gato_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='gato',
            name='foto',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
