# Generated by Django 3.0.3 on 2020-03-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200311_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
